### PR TITLE
Created using Colaboratory

### PR DESCRIPTION
**Pull request by christodd-nhsx**
Tried resaving this [url](https://colab.research.google.com/github/nhs-pycom/coding-club/blob/main/introduction-to-python/episode-7.ipynb) in the repo, but not sure if its going to work, as the code changes show for the merge show its now trying to reference this branch?

### CODE REVIEW

**Comment by craig-shenton** [comment]
hmm yep, might just remove the branch protection rules, not like this repo is a production level programme.

**Comment by christodd-nhsx** [comment]
Yeah, looks like the link doesn't update correctly when moving between branches. 

Ok, let me know when the branch protection has been removed. Ideally would be good before tomorrow afternoon as I'm presenting this session, but I can just give them the direct colab link if not.

**Comment by craig-shenton** [comment]
should be gone now

**Comment by christodd-nhsx** [comment]
Thats working now. Thanks for your help!

**Pull request merged**
